### ISSUE TITLE
[IPython] work out support for citations and math macros

### ISSUE THREAD

**Issue by cekees** [erdc/proteus#97]
should be able to get some support  for  gwatername.bib  and  ctmmath. @mfarthin I'm collecting some of these issues in the proteus issue tracker.

https://github.com/ipython/nbconvert-examples
# TODO
- [ ] ipynb with example of using a .bib file and \cite commands
- [ ] ipynb with example of using macros defined in a local .tex file that is included
- [ ] ipynb test with real gwatername.bib  and ctmmath.tex

**Comment by adimako** [comment]
@cekees this does not look very important. I recommend close it and if someone wants this functionality in, should be opened as a new issue. Since then there is the calico tool https://www.youtube.com/watch?v=86FTd1pcoZ4. Should be converted to "Calico tool implementation issue" https://www.youtube.com/watch?v=86FTd1pcoZ4. Closing this
